ARTICLES['bc-trade'] = {
  meta: 'Article · Trade Policy',
  title: 'Beyond the US Market: British Columbia’s Energy and Forestry Turn to Asia-Pacific',
  dek: "BC shows how gains from diversification can directly contribute to Canada's leading and aging industries and the provincial communities that power them.",
  body: `
  <p>As of July 2026, British Columbia’s lumber enters the United States while carrying duties of roughly 45 per cent. This is after anti-dumping and countervailing rates more than doubled last summer and a further tariff followed in October.<sup>1</sup></p>
  <p>It would be easy to treat this as part of the turbulence of the moment. But the softwood lumber dispute has recurred since the early 1980s, surviving free trade agreements, arbitration panels and decades of diplomacy.<sup>2</sup> These recent tariffs are, in many ways, the latest incarnation of a rather old problem — only now the issue has extended far beyond lumber.</p>
  <p>Selling more to the Asia-Pacific will not free British Columbia from the American market. The United States bought $28.7 billion of the province’s goods in 2024, and no Asian market comes close.<sup>3</sup> But it can reduce the province’s exposure to a single buyer, and, importantly, it can pay better. Two BC industries show how, both doing so from opposite directions: while energy is finding Asian customers for the first time, forestry has sold to Asia for a century and now is turning to high-value products that yield more gains from less quantity.</p>
  <div class="article-divider"></div>
  <h2>Liquefied Natural Gas: Making Better Use of What Exists</h2>
  <p>The transition to clean, net-zero energy won’t finish in days, and it won’t simply be driven by a few magic fuels. Liquefied natural gas (LNG) is not fully clean, but it produces substantially lower combustion emissions than most other conventional fuels.<sup>4</sup> Moreover, the countries buying it are not choosing between gas and solar panels. They are choosing between gas and coal, and that choice is more constrained than it looks from here.</p>
  <p>Japan, South Korea, and Taiwan have almost no domestic gas, relying predominantly on imports.<sup>5</sup> Recently, when Qatar halted production and shipping through the Strait of Hormuz stopped, they could not simply switch to renewables at short notice. They burned more coal instead, and Japanese coal generation rose 11 per cent in a single month.<sup>6</sup> Gas is what allows these countries to retire coal plants without risking their electricity supply. That is what a transitional fuel is for, and the transition is not a short one.</p>
  <div class="article-media">
    <img src="images/BC_Trade/BC_Graph.png" alt="Bar chart showing the approximate share of LNG cargoes shipped from Kitimat by destination, June 2025 to March 2026: South Korea 40%, Mainland China 25%, Japan 25%, Taiwan 7%." style="max-width:520px;">
  </div>
  <p>Beyond environmental contributions, the economic benefits have also begun to show. Since the first cargo left Kitimat at the end of June 2025, more than 100 shipments have followed.<sup>10</sup> Roughly two-fifths have gone to South Korea, with mainland China and Japan taking about a quarter each.<sup>11</sup> None have gone to the United States, because this is not redirected American gas. It is Western Canadian gas entering a market that was previously closed off, leveraging BC’s logistics efficiency and market proximity to become globally competitive.<sup>16</sup> The province now forecasts natural gas royalties rising 38 per cent next year, to about $1.3 billion, one of very few provincial revenue lines moving upward against a record $13.3 billion deficit.<sup>12</sup></p>
  <p>The money has also landed where it was needed. LNG Canada reports awarding more than $5.8 billion in contracts to British Columbia businesses, and $4.9 billion of that went to Indigenous-owned and local-area firms.<sup>13</sup> Haisla Chief Councillor Crystal Smith has said her nation was “tired of managing poverty.” It has since built an apartment complex, a health centre, and a $5-million language and culture centre.<sup>14</sup> The Haisla hold a majority stake in Cedar LNG, making it the largest Indigenous-majority-owned infrastructure project in Canada.<sup>15</sup> A few decades ago, such projects would have excluded the very communities whose land they ultimately required, but expansions today include these communities with a direct ownership stake.</p>
  <p>The benefits also extend to British Columbia’s extensive logistics industry. The transportation and warehousing sector employs about 156,000 people across 8,700 businesses in BC, and the province’s ports offer the fastest sailing times to Asia of anywhere in North America.<sup>16</sup> A terminal running at capacity needs roughly fifteen tankers a month, plus the pipeline crews, rail operators, terminal staff, and marine services behind them.<sup>17</sup> HaiSea Marine, a Haisla joint venture, holds a $500-million contract running battery-powered tugboats out of Kitimat harbour.<sup>13</sup> The goods produced by the LNG plants directly support the functioning of these logistics networks. Many of them would not survive on domestic demand, existing in these large numbers precisely because of the regular streams of shipments leaving for regions like Asia.</p>
  <div class="article-pull">None have gone to the United States, because this is not redirected American gas. It is Western Canadian gas entering a market that was previously closed off.</div>
  <p>There is also a longer horizon worth noting. Japan has legislated demand for synthetic methane, or e-methane, and aims to blend it into its gas supply this decade.<sup>7,8</sup> E-methane is chemically identical to natural gas, which means the same terminals and the same tankers that carry LNG from British Columbia today could carry e-methane tomorrow without modification.</p>
  <p>The goal should not be to plan a wave of new terminals, but to dispatch the capacity that is already underway in a way that meets both economic and environmental needs. Steps have already been taken to address the latter. Cedar LNG, near Kitimat, and Woodfibre LNG, near Squamish, are both being built to run on hydroelectricity rather than gas turbines. Woodfibre is designed for an emissions intensity of 0.04 tonnes of carbon dioxide equivalent per tonne of LNG and Cedar for 0.08, against a British Columbia regulatory benchmark of 0.16.<sup>9</sup> Few places in the world can supply this fuel with so little damage, because few have British Columbia’s clean grid and cold climate.</p>
  <div class="article-divider"></div>
  <h2>Forestry: Making More from Each Log</h2>
  <p>Forestry is British Columbia’s oldest industry, but it has been having a difficult decade. The province’s timber harvest has fallen to roughly 35 million cubic metres against an allowable annual cut of about 60 million.<sup>18</sup> Jobs closely track this harvest: as the public cut fell from 43 million cubic metres in 2022 to about 35 million in 2025, employment across the sector fell from roughly 101,000 to 85,000.<sup>19</sup> While American tariffs of 45 per cent have certainly taken their toll, they have only added to a situation that was already tight. Ultimately, trade policy cannot bring back trees.</p>
  <p>But a smaller harvest does not have to mean a smaller industry, and this is where markets outside the United States matter. Japanese homes are largely built either in the traditional post-and-beam style or in North American-style frame construction, and the post-and-beam method uses timber milled to different specifications entirely, sized in metric dimensions, and graded on visible characteristics like knots, discoloration, and wane.<sup>20</sup> That is demanding work, and British Columbia mills are good at it. Custom cutters in the province produce components for Japanese temples, along with windows and doors milled to precise specification.<sup>21</sup> In South Korea, 98 per cent of the lumber shipped from British Columbia is high grade.<sup>22</sup> While Asian demand for Canadian wood has slightly softened over the past decade, Canada Wood’s Bruce St. John reminds us that Japan still “gives the highest possible return to the industry in terms of the value of the lumber they import.”<sup>23</sup></p>
  <div class="article-media">
    <img src="images/BC_Trade/BC_Japan.jpg" alt="Interior hallway of a traditional post-and-beam Japanese home, with wooden beams, sliding shoji screens, and a polished wood floor.">
    <p class="article-media-caption">A traditional post-and-beam Japanese home.</p>
  </div>
  <p>Japan takes about 9 per cent of British Columbia’s forest product exports by value, and pays disproportionately for what it buys.<sup>24</sup> Trade agreements help in this. Under the Trans-Pacific Partnership, Japan eliminated tariffs on worked and finished wood immediately in 2018, while duties on ordinary lumber are still being phased out through 2033.<sup>25</sup> The agreement rewards processing. And because the 2020 United States-Japan trade deal left Japanese wood tariffs untouched, Canadian mills currently sell into Japan on better terms than American ones.<sup>26</sup> Korean tariffs on Canadian wood finished phasing out last year.<sup>27</sup></p>
  <p>British Columbia’s pivot to these markets has already yielded significant gains for the province. Value-added wood manufacturing contributed more than $1.3 billion to provincial GDP in 2024, and roughly 1.5 million cubic metres of timber has moved through a dedicated provincial program for value-added producers since 2023.<sup>28</sup> The preservation of this sector directly supports quality of life in many BC communities. Forest sector jobs pay about 50 per cent above the provincial average, ~$116,000 against ~$77,000, and they sit in towns where comparable wages are scarce. Moreover, the sector employs Indigenous workers at nearly twice the rate of any other industry in the province.<sup>29</sup> Each of those jobs supports other industries as well — most of all logistics, since finished wood bound for Asia still has to be trucked, railed, and loaded onto ships.<sup>30</sup> As Forests Minister Ravi Parmar put it, the province’s path forward “can’t just be providing dimensional lumber to Americans. We have to make more in B.C.”<sup>28</sup></p>
  <p>What is most encouraging is that there is still room to grow. While many lucrative gains have so far been in East Asia, other countries also offer promising near-term opportunities. India, for instance, presents an increasingly growing demand for international logs, lumber, and wood products. Its imports have risen from $630 million to $2.3 billion over two decades, and its own timber supply is thinning while its furniture and construction sectors expand.<sup>31</sup> British Columbia’s cedars, hemlock, and Douglas fir are well suited to the knot-free uses Indian buyers want.<sup>32</sup> Japan and Korea have already shown what a demanding customer is worth, which is why it would be prudent to court India as the next one.</p>
  <div class="article-divider"></div>
  <h2>What the Two Cases Share</h2>
  <p>The United States is still a key partner for both industries. After all, the American market is close, enormous, and remains British Columbia’s largest customer by a sizeable margin.</p>
  <p>Nonetheless, both industries have shown the benefits that can come from broadening Canada’s trading footprint. One is new and finding its first customers across the Pacific. The other is old, working with a smaller resource, and getting more from each unit of it than it used to. Both are demonstrating that the benefits are not restricted to a single scenario or context; rather, they can be as multi-faceted as the industries that deliver them.</p>
  <p>Reducing exposure to a single buyer is not only a matter of insurance against the next round of tariffs. It is also, in an ordinary course, a way to earn more to improve the lives of Canadians and the global standing of Canada.</p>
  <div class="footnotes">
    <p class="footnotes-label">Sources</p>
    <p><sup>1</sup> Global Affairs Canada, “Frequently asked questions – Softwood lumber,” updated 10 July 2026.</p>
    <p><sup>2</sup> Congressional Research Service, “U.S.–Canada Softwood Lumber Trade: Current Issues for Congress,” Report R48781, December 2025.</p>
    <p><sup>3</sup> BC Stats, “British Columbia and U.S. Tariffs,” 26 March 2025.</p>
    <p><sup>4</sup> U.S. Energy Information Administration, “Carbon Dioxide Emissions Coefficients.”</p>
    <p><sup>5</sup> Center on Global Energy Policy, Columbia University SIPA, “Asia’s Gas Shock Playbook: Coal, Curtailment, and Competing for LNG,” April 2026.</p>
    <p><sup>6</sup> Rystad Energy analysis, reported in Eco-Business, June 2026.</p>
    <p><sup>7</sup> Japan Gas Association, “2030 Vision”; Japan’s Hydrogen Society Promotion Act (May 2024).</p>
    <p><sup>8</sup> Mitsubishi Corporation, news release, 29 November 2022.</p>
    <p><sup>9</sup> Woodfibre LNG, “Roadmap to Net Zero”; Canadian Energy Centre and EnergyNow on Cedar LNG.</p>
    <p><sup>10</sup> LNG Prime, “LNG Canada ships 100th cargo,” 18 June 2026.</p>
    <p><sup>11</sup> Werner Antweiler, Sauder School of Business, University of British Columbia, 27 March 2026.</p>
    <p><sup>12</sup> British Columbia Ministry of Finance, “Budget and Fiscal Plan 2026/27–2028/29,” 17 February 2026.</p>
    <p><sup>13</sup> LNG Canada, “First Cargo Puts Canada on the Map of LNG Exporting Nations,” 30 June 2025.</p>
    <p><sup>14</sup> Crystal Smith, Chief Councillor, Haisla Nation, reported in Business in Vancouver, June 2024.</p>
    <p><sup>15</sup> CBC News, “Pembina, Haisla First Nation greenlight proposed LNG project,” June 2024.</p>
    <p><sup>16</sup> Government of British Columbia, “Look West Strategy,” 2026.</p>
    <p><sup>17</sup> RBC Capital Markets analyst Michael Harvey, reported in The Globe and Mail, 18 March 2026.</p>
    <p><sup>18</sup> BC Council of Forest Industries, statement on British Columbia Budget 2026, February 2026.</p>
    <p><sup>19</sup> BC Council of Forest Industries, “Rooted in BC: Economic Impact of Forestry,” Technical Report, 7 April 2026.</p>
    <p><sup>20</sup> USDA Foreign Agricultural Service, GAIN Report JA2025-0023, May 2025.</p>
    <p><sup>21</sup> Government of British Columbia, news release 2026FOR0036-000816, July 2026.</p>
    <p><sup>22</sup> Canada Wood Group, canadawood.org.</p>
    <p><sup>23</sup> Bruce St. John, President, Canada Wood Group, quoted in Wood Central, February 2026.</p>
    <p><sup>24</sup> B.C. Ministry of Forests, Economics and Trade Branch, “B.C. Forest Product Exports – December 2025,” 23 February 2026.</p>
    <p><sup>25</sup> Global Affairs Canada, “CPTPP partner: Japan.”</p>
    <p><sup>26</sup> USDA Foreign Agricultural Service, GAIN Report JA2025-0023, May 2025.</p>
    <p><sup>27</sup> Canadian Trade Commissioner Service and Global Affairs Canada, Canada-Korea Free Trade Agreement.</p>
    <p><sup>28</sup> Government of British Columbia, news release 2026FOR0036-000816, July 2026.</p>
    <p><sup>29</sup> BC Council of Forest Industries, “Rooted in BC: Economic Impact of Forestry,” Technical Report, 7 April 2026.</p>
    <p><sup>30</sup> BC Council of Forest Industries, “Rooted in BC: Economic Impact of Forestry,” Technical Report, 7 April 2026.</p>
    <p><sup>31</sup> USDA Foreign Agricultural Service, “India: Wood and Wood Products Update 2024,” GAIN Report IN2024-0026.</p>
    <p><sup>32</sup> Canadian Trade Commissioner Service, “Canadian wood products find a growing market in India.”</p>
  </div>
`
};
