ARTICLES['brief-long'] = {
  meta: 'Policy Brief · Energy & Climate',
  title: "The Hydro-Emissions Tension: Addressing Structural Vulnerabilities in Canada's Net-Zero Transition — Long Version",
  charts: (id) => {
    if (id !== 'brief-long') return;
    const el1 = document.getElementById('briefLineChart');
    if (el1) charts.briefLine = new Chart(el1, makeLineConfig());
    const el2 = document.getElementById('briefProjChart');
    if (el2) charts.briefProj = new Chart(el2, JSON.parse(JSON.stringify(projConfig)));
  },
  body: `
<div class="article-links">
  <button class="article-link-btn" onclick="showArticle('brief-short')">View Short Brief</button>
  <button class="article-link-btn" onclick="showArticle('hydro')">View Op-ed</button>
</div>

  <h2>Summary</h2>
  <p>Canada's electricity grid is quite clean due to a heavy reliance on hydro generation, but recent droughts have started to highlight a structural risk: when hydro generation drops, the system often falls back on fossil generation or imports to fill the shortfall. This is already visible in provinces like British Columbia and Manitoba, and it risks becoming more pronounced as electricity demand rises with electrification. The issue is not hydro itself, but the limited availability of reliable, non-emitting backup capacity and the fragmented structure of the national grid. Without expanding other clean energy sources, improving interprovincial transmission, and revising how grid planners account for hydro's weather-dependence, even short-term reductions in hydro output can lead to higher emissions if not offset by other clean sources. Over time, this could leave Canada structurally more dependent on fossil fuels during periods of supply pressure.</p>

  <h2>Introduction</h2>
  <p>Canada's electricity sector has achieved several notable gains in its quest toward sustainability. Since 2005, greenhouse gas emissions from electricity generation have fallen by 58%, which is the single largest sectoral reduction in the Canadian economy over that period.<sup>1</sup> The grid that powers Canadian homes and industries is, in a normal year, over 80% non-emitting.<sup>2</sup> Historically, hydropower accounted for nearly 60% of the power grid.<sup>3</sup> In individual provinces like British Columbia and Manitoba, the contribution of hydro generation reaches 90% and beyond.<sup>4</sup></p>
  <p>However, the past few years have shown why this dependence on hydro poses a vulnerability. The years 2023 and 2025 stand out in particular, both featuring droughts and some of the lowest hydro generation levels since Statistics Canada's current series began in 2016. Conversely, combustible fuel generation rose to its highest level since 2016 in 2025. Canada became a net electricity importer during multiple months of 2024 and 2025, the first time this had occurred in the current era.<sup>5</sup> This paper examines the pattern indicated by the data and finds that it reflects a structural risk: Canada's electricity system is highly reliant on hydro generation for meeting its clean energy goals, but hydro's variability and the absence of clean fallback solutions can contribute to increased reliance on fossil fuel generation. As the net-zero transition continues, accounting for variations in hydro generation while also diversifying beyond hydro can make the grid more reliable in delivering clean energy even when under pressure.</p>

  <h2>The Structural Risk</h2>
  <p>The scale of the shift in the last few years is measurable. Canada's hydroelectric generation peaked at 392 TWh in 2017. By 2024 it had fallen to 341.8 TWh: a drop of roughly 50 TWh from that peak.<sup>6</sup> Expressed as a share of total generation, hydro fell from 61% in 2022 to just under 55% in 2025, a series low. At the same time, combustible fuels moved in the opposite direction, rising from 137.8 TWh in 2022 to a series-high 143.4 TWh in 2025.<sup>6</sup></p>
  <p>A simple way to illustrate the scale of this vulnerability is to translate hydro variability into a supply shock. Using 2024 hydro generation of 341.8 TWh, a 10% decline would imply a shortfall of roughly 34.2 TWh.<sup>6</sup> That is about one-quarter of 2025 combustible-fuels generation (143.4 TWh), meaning even a moderate drought can create a gap large enough to require substantial replacement, which is currently often met by fossil generation or higher-emissions imports.</p>
  ${lineChartHTML('briefLineChart')}
  <p>British Columbia illustrates one version of this dynamic. The province generates the vast majority of its electricity from hydroelectric dams, with almost no domestic fossil backup. When Williston Reservoir inflows hit record lows, BC Hydro faced a generation deficit of 10,430 GWh and covered it by importing close to 25% of provincial electricity demand at a cost of approximately $1.38 billion.<sup>7</sup> A large share of those imports came from the United States and Alberta, whose grid ran at approximately 74.7% natural gas in 2024, with a carbon intensity more than four times the Canadian national average.<sup>8</sup> The result is a meaningful fossil footprint that is not reflected in provincial generation-based emissions accounting. Provincial emissions inventories count only what is generated within a province's borders, so the carbon embedded in those imports does not appear in BC's official figures. The $1.38 billion paid for imports is the financial record of a shortfall that likely increased reliance on fossil fuel generation outside the province.</p>
  <p>Manitoba provides a more important example by showing how current decisions are reinforcing this systemic dynamic for the future. The province generates around 97% of its electricity from hydro.<sup>9</sup> This presently makes it one of the cleanest grids in Canada, but the concentration of hydro also means there is no domestic clean alternative when precipitation falls short. In response, Manitoba Hydro has proposed a $3 billion combustion turbine facility at Brandon, designed specifically to provide dispatchable backup when hydro is insufficient, with natural gas as the lowest-cost fuel option under consideration.<sup>10</sup> The utility's own planning documents describe this dispatchable capacity as "essential" to meeting demand through the next decade.<sup>11</sup></p>
  <p>This measure is understandable today given that clean and renewable sources, while rapidly growing, still pose practical issues regarding costs and reliability. But this measure also reveals why clean alternatives must be proactively identified and developed. By turning to fossil fuels to cover the future shortfalls of hydro, the province starts creating a system that, when under pressure, leads to high emissions under stress conditions. Such design decisions sustain the presence of fossil fuels, making them recurrent players because the irregularity associated with hydro generation is a recurring issue.</p>

  <h2>Electrification and the Compounding Risk</h2>
  <p>The risks outlined above are compounded by Canada's broader push toward electrification. Electrification is a key component of the federal government's environmental strategy. The Clean Electricity Regulations, finalized in December 2024, establish emission limits on electricity generating units beginning in 2035, with a net-zero grid target of 2050.<sup>12</sup> Running alongside this is a plan to move transportation, space heating, and industrial processes off fossil fuels and onto electricity, which will require substantially more electricity than Canada currently produces. The Canada Energy Regulator (CER) projects that electricity demand will grow between 26% and 44% by 2050 relative to 2023 levels.<sup>13</sup> BC Hydro's own filings project a 15% increase in provincial electricity demand by 2030 alone, driven by electric vehicles, population growth, and restrictions on natural gas for heating.<sup>14</sup></p>
  <p>The problem is that this rising demand will land on a grid whose clean foundation has shown vulnerability under stress conditions. The below-average precipitation years demonstrated that a 10% drop in hydro output — consistent with what Statistics Canada recorded nationally in 2023 — leaves a gap of tens of terawatt-hours that the current system fills largely with fossil fuels.<sup>15</sup> CER scenario projections show that electricity demand will rise faster than hydro generation, which would make the grid more sensitive to future hydro declines simply because the baseline requirements are higher.<sup>13,16</sup> As total grid load grows with electrification and outpaces the increase in hydro capacity, the grid becomes more sensitive to droughts, even those of the same intensity as today. As a result, it requires an earlier intervention from other sources, and as it stands today, these other sources consist largely of fossil fuels. In short, while electrification remains essential for decarbonization overall, without parallel expansion of reliable clean capacity, it may increase reliance on fossil fuels during supply stress.</p>
  ${projChartHTML('briefProjChart')}

  <h2>Possible Solutions</h2>
  <p>While hydroelectricity has a crucial role to play, a lack of attention has been given to clean sources that replace hydro when it underperforms. To be sure, fossil fuels are an appropriate solution in some cases, but presently they are a common fallback solution. Besides expanding the storage capacity of wind and solar and funding clean yet relatively undeveloped sources like geothermal energy,<sup>17</sup> there are two other key steps that can be begun immediately to resolve this issue.</p>
  <p>The first concerns geographic fragmentation. Hydro conditions across Canada are not uniform. A drought affecting British Columbia's reservoirs may not affect Quebec's or Manitoba's to the same extent in the same year. Moreover, provinces like New Brunswick and Ontario (with its nuclear plants) can supply clean energy from sources other than hydro. A grid with sufficient interprovincial transmission capacity could allow clean surplus generation in one region to cover deficits in another, reducing the need for provinces to turn to fossil fuels when their own hydro underperforms. At present, Canada operates three largely separate regional grids — Western, Eastern, and Québec — with limited east-west interconnection, and provinces trade more electricity with US states than with each other.<sup>19</sup> Modelling by the Canada Electricity Advisory Council and the Canadian Climate Institute suggests that expanded interprovincial interties could reduce system-wide emissions and lower industrial electricity prices, while also increasing resilience to precisely the kind of regional supply stress seen in recent drought years.<sup>20</sup></p>
  <p>Energy policy largely falls under the jurisdiction of provinces, and so implementing the first measure would require addressing two key provincial concerns: cost burdens and a loss of flexibility.<sup>22</sup> Because transmission investments are evaluated primarily on provincial cost-benefit grounds — even when their largest gains are national — provinces have limited incentive to build interties on their own, which makes federal financing and coordination essential. At the same time, there must be room for provincial governments to make tailored contracts that align with their specific economic and environmental goals.</p>
  <p>The second response does not require new infrastructure but a change in planning assumptions. Utilities and regulators have often treated hydro as highly reliable firm capacity, but greater attention must be given to hydrological variability. Under that assumption, utilities and regulators have had little reason to require non-fossil backup capacity for drought scenarios, since hydro was not expected to fail. The 2023–2025 data challenge that assumption, and the Clean Electricity Regulations have begun to reflect it: one of the regulatory flexibilities explicitly included is the ability for electricity units to bank compliance credits for use in drought years when hydro falls short.<sup>21</sup> If grid planning frameworks followed the same logic and accounted for hydro's variability in drought scenarios, the consequence can be direct: utilities would be required to secure non-fossil backup for periods when hydro underperforms, rather than defaulting to the cheapest dispatchable generation when a drought arrives. That is the condition under which fossil fuels currently fill the gap, and changing the planning assumption can meaningfully change it.</p>

  <h2>Conclusion</h2>
  <p>Canada's electricity grid is cleaner than most, and the progress made since 2005 is substantial. Recent years, however, indicate that this performance is partly contingent on hydroelectric availability. Periods of reduced precipitation have coincided with increased fossil fuel generation and imports, consistent with a grid that lacks sufficient clean alternatives when hydro underperforms. British Columbia covered a quarter of its demand through high-carbon imports during low-water conditions, while Manitoba has proposed new dispatchable gas capacity to address similar risks going forward. These are not isolated decisions but expressions of an underlying design gap that should be addressed as the transition to clean energy continues. Electrification is likely to place greater pressure on that gap by raising the overall load that must be met when hydro falls short. Addressing it will require expanding non-emitting generation capacity, strengthening interprovincial transmission so that clean surpluses in one basin can cover deficits in another, and revising the planning assumption that hydro will always deliver.</p>

  <div class="footnotes">
    <p class="footnotes-label">Sources</p>
    <p><sup>1</sup> Environment and Climate Change Canada. National Inventory Report 1990–2023: Greenhouse Gas Sources and Sinks in Canada (2025). canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions.html</p>
    <p><sup>2</sup> Natural Resources Canada. Powering Canada's Future: A Clean Electricity Strategy. natural-resources.canada.ca/energy-sources/powering-canada-s-future-clean-electricity-strategy</p>
    <p><sup>3</sup> Statistics Canada. Electric Power Generation, Monthly Generation by Type of Electricity, Table 25-10-0015-01. Hydro share: 61.3% in 2022. statcan.gc.ca</p>
    <p><sup>4</sup> Canada Energy Regulator. Renewable Energy in Canada – British Columbia; Renewable Energy in Canada – Manitoba. cer-rec.gc.ca</p>
    <p><sup>5</sup> Statistics Canada. Electricity Generation from Combustibles and Renewables Sharply Increase Amid Another Dry Year: Electricity Year in Review 2025. statcan.gc.ca/o1/en/plus/9117</p>
    <p><sup>6</sup> Statistics Canada. Table 25-10-0015-01 / Electricity Year in Review 2025. Hydro: 392.2 TWh (2017 peak), 341.8 TWh (2024); combustibles: 137.8 TWh (2022), 143.4 TWh (2025 series high). The 34.2 TWh shortfall figure is derived from the 2024 hydro total using a 10% decline assumption consistent with the 2023 national decline recorded by Statistics Canada.</p>
    <p><sup>7</sup> BC Hydro. 2024/25 First Quarter Report. bchydro.com; Energy Futures Institute / BC Utilities Commission documents filed by BC Hydro, reported by Business in Vancouver, December 2, 2024. biv.com</p>
    <p><sup>8</sup> Energy Futures Institute / BC Utilities Commission documents filed by BC Hydro, reported by Business in Vancouver, December 2, 2024; Global News, November 29, 2024; Canada Energy Regulator, Provincial and Territorial Energy Profiles – Alberta. cer-rec.gc.ca (Alberta carbon intensity 470 g CO₂e/kWh vs. 100 g national average; Alberta gas share 74.7% in 2024).</p>
    <p><sup>9</sup> Canada Energy Regulator. Renewable Energy in Canada – Manitoba. cer-rec.gc.ca. Hydro: 96.9% of generation in 2023.</p>
    <p><sup>10</sup> CBC News, November 21, 2025; CBC News, February 27, 2025.</p>
    <p><sup>11</sup> Manitoba Hydro. Brandon Dispatchable Capacity Project. hydro.mb.ca/community/engagement/brandon-dispatchable-capacity</p>
    <p><sup>12</sup> Government of Canada. Clean Electricity Regulations (SOR/2024-263), finalized December 2024. Emission limits on generating units apply from 2035; net-zero grid target is 2050. canada.ca/en/environment-climate-change/corporate/transparency/strategic-environmental-economic-assessments/clean-electricity-regulations</p>
    <p><sup>13</sup> Canada Energy Regulator. Canada's Energy Future 2026: Executive Summary. cer-rec.gc.ca. Electricity demand grows 26% (Lower scenario) to 44% (Current Measures) from 2023 to 2050.</p>
    <p><sup>14</sup> Energy Futures Institute / BC Utilities Commission documents filed by BC Hydro, reported by Business in Vancouver, December 2, 2024.</p>
    <p><sup>15</sup> Statistics Canada. Electricity Supply and Disposition, 2023, released October 22, 2024. National hydro generation fell 9.3% year-over-year. statcan.gc.ca</p>
    <p><sup>16</sup> Canada Energy Regulator. Canada's Energy Future 2023, Current Measures scenario: hydro ~440 TWh by 2050; total generation ~973 TWh. cer-rec.gc.ca; Statistics Canada, Table 25-10-0015-01 for 2025 baseline.</p>
    <p><sup>17</sup> Canada Energy Regulator. Market Snapshot: Geothermal Power is Stable and Low Carbon, but What is its Potential in Canada? cer-rec.gc.ca; RBC Climate Action Institute / Canadian Geothermal Energy Association. Geothermal Energy Surges: Canada's Potential in a Promising Baseload Power Source (2026). rbc.com</p>
    <p><sup>18</sup> Ontario Power Generation. Darlington SMR Project. opg.com; NB Power. Advanced Small Modular Reactors. nbpower.com</p>
    <p><sup>19</sup> Canadian Climate Institute. Connecting Regional Electricity Grids in Canada (2025). climateinstitute.ca</p>
    <p><sup>20</sup> Canada Electricity Advisory Council. Powering Canada: A Blueprint for Success (May 2024). natural-resources.canada.ca</p>
    <p><sup>21</sup> Government of Canada. Clean Electricity Regulations: Maintaining Reliability. canada.ca/en/services/environment/weather/climatechange/climate-plan/clean-electricity/regulations-reliability.html</p>
    <p><sup>22</sup> Canadian Climate Institute. How Canada Can Build Electricity Transmission to Unlock Nation-Building Projects (2025). climateinstitute.ca</p>
  </div>
`
};
